<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(required)_btn btn-sm btn-icon btn-bg-light</name>
   <tag></tag>
   <elementGuidId>8192de34-b205-4005-a42c-f4d1671395a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-icon.btn-bg-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div[10]/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ab2304b-8b62-4b40-98a1-880e96f74917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-icon btn-bg-light</value>
      <webElementGuid>c931d73a-f945-42c9-a26b-3e467e7f4adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;row m-0 mt-25 p-5 bg-white e-form-container&quot;]/div[@class=&quot;mt-5 px-0&quot;]/div[@class=&quot;row vcp mx-0 py-4 d-flex justify-content-between me-3 risk-assessment-title&quot;]/div[@class=&quot;col-2 col-md-1&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;px-0 col-6&quot;]/button[@class=&quot;btn btn-sm btn-icon btn-bg-light&quot;]</value>
      <webElementGuid>2722f134-1ea3-45e1-af27-94cc518766bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div[10]/div/div[2]/div/div/button</value>
      <webElementGuid>523e0ec5-a220-4513-9703-c285495f4824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(required)'])[1]/following::button[1]</value>
      <webElementGuid>72854988-18f4-4c2d-8d0a-71caa4667926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRUCK DUMP BODY / MODULE IS FREE OF DIRT AND MATERIAL BUILD UP (EMPTY BODY)'])[1]/preceding::button[2]</value>
      <webElementGuid>ccd0fe39-4ec0-4935-b7ed-2943f099573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>821e89ff-0943-4d8f-b28a-b81d22538acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
