<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Online_ring</name>
   <tag></tag>
   <elementGuidId>3cda0a72-7bf5-4d29-b44d-70aa3fad103a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ring</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slot-container']/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9e5a0be-1389-4a2c-b643-336cec2f94ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ring</value>
      <webElementGuid>2a09dd15-cf22-43be-bb9f-96a576655f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot-container&quot;)/div[@class=&quot;d-flex flex-column justify-content-center align-items-end camera-container&quot;]/div[@class=&quot;w-9 py-3 d-flex flex-column justify-content-center align-items-center bg-dark&quot;]/div[@class=&quot;photo-button mb-60-percent&quot;]/div[@class=&quot;ring&quot;]</value>
      <webElementGuid>95ae9042-af79-4ed9-8596-1acb97a25760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot-container']/div/div/div/div[2]</value>
      <webElementGuid>67a8d388-0bee-4337-bd53-e63a03f5c0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::div[16]</value>
      <webElementGuid>18c95743-e02f-4211-9d2e-383be3ef46d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ben Neill'])[1]/preceding::div[19]</value>
      <webElementGuid>caf074b2-6ef6-4146-8930-a79dec23e689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>c74f6ee1-ee96-4105-9fba-016d964b4c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
