<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c50a99ee-e455-4674-98c7-9c7330ca64f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slot-container']/div/div/div[2]/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a0a5632e-e611-47ff-af12-c8309ee8a0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>media/svg/dma/camera/photo_camera.svg</value>
      <webElementGuid>5ec5cd11-ff95-410d-a695-c652dcd82a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot-container&quot;)/div[@class=&quot;d-flex flex-column justify-content-center align-items-end camera-container&quot;]/div[@class=&quot;w-9 py-3 d-flex flex-column justify-content-center align-items-center bg-dark&quot;]/div[@class=&quot;photo-button mb-2&quot;]/div[@class=&quot;ring d-flex justify-content-center&quot;]/img[1]</value>
      <webElementGuid>547260fe-f8b5-45ed-b590-1133878d579f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot-container']/div/div/div[2]/div[2]/img</value>
      <webElementGuid>6a6c5046-ef2f-40d6-a56c-b7acfd9c548a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>89586966-b0c6-4fd0-b730-2354bb2135dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'media/svg/dma/camera/photo_camera.svg']</value>
      <webElementGuid>b172273d-f3de-436d-af68-13bced35bc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot-container']/div/div/div/div[2]/img</value>
      <webElementGuid>14c8ab9f-307f-4da8-8b46-4c8c3604eccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
