<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Labour Personnel Name_form-control bo_aa2426</name>
   <tag></tag>
   <elementGuidId>468f0bad-88db-42c2-9ffd-a975a90b2c97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.border-right-0.border.form-floating</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74995096-f48e-4a48-83ed-1ee069a494a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-right-0 border form-floating</value>
      <webElementGuid>bf3f5255-f02a-41f6-805b-5dd65005a4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>915a99a5-7172-409f-84a1-f919761dc74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-collapse-content-3766&quot;)/div[@class=&quot;el-collapse-item__content&quot;]/div[@class=&quot;p-2 me-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pe-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;input-group col-md-4&quot;]/div[@class=&quot;form-floating flex-fill&quot;]/input[@class=&quot;form-control border-right-0 border form-floating&quot;]</value>
      <webElementGuid>775b56b8-fb64-4a21-ad07-d554bfbc3c38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>f058928a-04d1-4a4a-a9f7-3f5e0cc281da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-3766']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>3ceed608-b915-461d-afb3-c9f1632332be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>0423f0fc-bc7c-4edf-b022-0f4906ff79af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>c5f859e0-9025-4e4b-989e-5ffe1e801528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
