<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter IronLake</name>
   <tag></tag>
   <elementGuidId>7aa149f2-326c-41a9-9d6d-00930cabf15d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div[2]/div/div/div[3]/a/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-go-to-apps.btn-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41f324ab-4733-488d-8af9-ac451723a651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>92bfa1e9-d98d-4855-bbb7-73909c86bfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-go-to-apps btn-label</value>
      <webElementGuid>0897414f-f00c-4164-ac03-8336be3824a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter IronLake</value>
      <webElementGuid>4717917b-fb21-4864-a9d0-fcef71af7c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;row gy-5 g-xl-8 m-2 h-250px&quot;]/div[@class=&quot;col-6 col-sm-4 col-md-3 col-lg-20-percent col-xl-2 pe-2 col-xxl-2 ps-0&quot;]/div[@class=&quot;card h-100&quot;]/div[@class=&quot;card-footer&quot;]/a[1]/a[@class=&quot;btn btn-sm btn-go-to-apps btn-label&quot;]</value>
      <webElementGuid>37bc7581-1a43-4b83-a8f6-4d66c21f6b86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div[2]/div/div/div[3]/a/a</value>
      <webElementGuid>c22b57c7-2655-4ffe-84cc-38e26b77fae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter IronLake')]</value>
      <webElementGuid>cd72ee73-fb25-45f4-a006-5a8f0beaa981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Ben Neill!'])[1]/following::a[2]</value>
      <webElementGuid>c6c27f66-a76a-4a40-ab7f-7ee8f1f4d5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[3]</value>
      <webElementGuid>2b315e0b-2957-48c3-9243-2e73332d460f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Technology Platform that provides critical component condition information.'])[1]/preceding::a[1]</value>
      <webElementGuid>cb65eaaf-2c6a-4ed6-9547-508d7604c108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter IronPortal'])[1]/preceding::a[1]</value>
      <webElementGuid>9e4ff086-636b-413f-96f3-3ae85c747ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter IronLake']/parent::*</value>
      <webElementGuid>c25415c8-c3fc-42f0-b119-094ed149a799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[5]</value>
      <webElementGuid>77a99fba-432e-4cbc-8a0b-3c20db866828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/a</value>
      <webElementGuid>bf87ac57-aaf0-449a-9d2f-265258a413ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Enter IronLake' or . = 'Enter IronLake')]</value>
      <webElementGuid>8dce91d4-b9eb-4f38-86f9-41c717b37032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
