<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Online_ring d-flex justify-content-center</name>
   <tag></tag>
   <elementGuidId>cb71d129-c4af-4253-8135-93433be03696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slot-container']/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ring.d-flex.justify-content-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0cd1922-f7f9-4138-b425-82115b6852b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ring d-flex justify-content-center</value>
      <webElementGuid>42e04e63-8c89-497d-8902-f349b36a17c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot-container&quot;)/div[@class=&quot;d-flex flex-column justify-content-center align-items-end camera-container&quot;]/div[@class=&quot;w-9 py-3 d-flex flex-column justify-content-center align-items-center bg-dark&quot;]/div[@class=&quot;photo-button mb-2&quot;]/div[@class=&quot;ring d-flex justify-content-center&quot;]</value>
      <webElementGuid>671f2378-f316-43a8-b8f9-068aef6a6356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot-container']/div/div/div[2]/div[2]</value>
      <webElementGuid>ce3728e1-5ee2-417b-b83b-1648435f7ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::div[13]</value>
      <webElementGuid>f6492999-f035-43e7-8b0c-91720a65fe17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ben Neill'])[1]/preceding::div[16]</value>
      <webElementGuid>879e3934-f413-4666-933c-7c8fbbb3e39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>a0b18728-b6bb-4392-869f-5c86e0ce6790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
