<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tom Woodward</name>
   <tag></tag>
   <elementGuidId>f19a94c5-2dc3-4d7d-93f4-783ac8fcb721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-collapse-content-1653']/div/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.option-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0108f96e-6eda-466c-968a-d8d1127544d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-wrapper</value>
      <webElementGuid>eb7d52fe-6d9b-48cf-8348-7057332d703f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tom Woodward</value>
      <webElementGuid>d8906838-4bae-4a48-88eb-35eda492796a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-collapse-content-1653&quot;)/div[@class=&quot;el-collapse-item__content&quot;]/div[@class=&quot;p-2 me-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pe-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;input-group col-md-4&quot;]/div[@class=&quot;option-wrapper&quot;]</value>
      <webElementGuid>e851ec7b-93e0-46bf-b68d-43037379b46e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-1653']/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>8069ece4-9746-43cf-8bb8-ecc04e779b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labour Personnel Name'])[1]/following::div[1]</value>
      <webElementGuid>91afe088-7493-45ae-97dc-437637f6f9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Labour Personnel'])[1]/following::div[9]</value>
      <webElementGuid>8e45c21f-ee59-4cbe-ae78-eb76da7047be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actual Service Start (each labour personnel)'])[1]/preceding::div[3]</value>
      <webElementGuid>c71a35a7-9d04-46c1-9ae9-0f6078288900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>d8f615cd-1c04-4d6d-9a44-d9cc8843d98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tom Woodward' or . = 'Tom Woodward')]</value>
      <webElementGuid>703b15bf-d8de-43f6-a6bc-94f82de0a760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
