<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>78e5427f-1569-4084-802f-05a5b5f2a6ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slot-container']/div/div/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33f9b2f3-7711-4ac9-b928-6dc4546ebfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>media/svg/dma/camera/photo_camera.svg</value>
      <webElementGuid>52c35bea-38cf-40f4-bab5-101f697c1ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot-container&quot;)/div[@class=&quot;d-flex flex-column justify-content-center align-items-end camera-container&quot;]/div[@class=&quot;w-9 py-3 d-flex flex-column justify-content-center align-items-center bg-dark&quot;]/div[@class=&quot;photo-button mb-2&quot;]/div[@class=&quot;ring d-flex justify-content-center&quot;]/img[1]</value>
      <webElementGuid>835c7436-97b1-4c49-ab3e-dd2b0e276fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot-container']/div/div/div[2]/div[2]/img</value>
      <webElementGuid>21fec269-67e9-446b-9088-e63e4ad87ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>aa2ae66b-ea65-491f-863c-1458dcd19246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'media/svg/dma/camera/photo_camera.svg']</value>
      <webElementGuid>60553777-9108-42ce-bb63-d59269bfa867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot-container']/div/div/div/div[2]/img</value>
      <webElementGuid>2da9ffc2-4c8f-48c5-9812-3ae4bf935470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
