<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Labour Personnel Name_form-control py_2519fb</name>
   <tag></tag>
   <elementGuidId>42c315d1-28f9-4965-97b5-7b6dbdadb6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.py-2.border-left-0.border</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37e7e88a-908e-4a35-be44-4a5f8f7ee41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control py-2 border-left-0 border</value>
      <webElementGuid>99dc2f46-1442-4dec-b047-0033ec61ce05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83933a32-a846-418c-b49a-4185157fec74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search here..</value>
      <webElementGuid>fecc140b-bfe3-402c-ab1c-ccb67a5116f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-collapse-content-1653&quot;)/div[@class=&quot;el-collapse-item__content&quot;]/div[@class=&quot;p-2 me-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pe-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;input-group col-md-4&quot;]/div[@class=&quot;option-wrapper&quot;]/div[@class=&quot;w-100 top-0&quot;]/div[@class=&quot;input-group col-md-4&quot;]/input[@class=&quot;form-control py-2 border-left-0 border&quot;]</value>
      <webElementGuid>405d7173-2add-4838-b0ac-737409e7bd49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>f6272177-6f41-4468-82b5-d2435f13f72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-1653']/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>0da90ab3-10ae-4355-9017-0c0351c92b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>10ba35b6-efe6-4870-86f7-ae37fcbffb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search here..']</value>
      <webElementGuid>dfeabd18-2d01-48ec-8d2d-e059fa899057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-3766']/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>6f29faf4-7b60-445a-8a1e-ddc59ccb12e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
