<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Task</name>
   <tag></tag>
   <elementGuidId>62cb6fcd-c9b7-40f7-943a-5c4fd200e736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#kt_header_menu']/div[4]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d5c09b3-8c1e-450a-b99a-cd62183069d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>44f57e4e-fd16-44b7-893e-93277edc5101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Task</value>
      <webElementGuid>4160b6f0-2564-4af9-aff2-792f8b7edb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_aside_menu_wrapper&quot;)/div[@id=&quot;#kt_header_menu&quot;]/div[@class=&quot;menu-item&quot;]/div[@class=&quot;menu-item menu-accordion&quot;]/span[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>079d328f-eb6c-4673-a2fe-086143fd865a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#kt_header_menu']/div[4]/div/span</value>
      <webElementGuid>9c27a4e0-13ee-43e5-9387-a0c06bce330c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Strategy'])[1]/following::span[1]</value>
      <webElementGuid>fd340670-9c96-47dd-a5b9-cb2265adeca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance'])[1]/following::span[5]</value>
      <webElementGuid>6a9b26e3-974d-4ad1-bf8f-c1d85cc9170e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding Service'])[1]/preceding::span[6]</value>
      <webElementGuid>edb55ddd-97e5-407e-9e34-9ad80ba9ebdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span</value>
      <webElementGuid>9d1e6b11-3e81-410c-8b81-b9d62bbe3942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Task' or . = 'Task')]</value>
      <webElementGuid>bed30ec3-4931-4429-89e2-e6e6380dbd9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
