<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Equipment_bottom-menu-item-icon</name>
   <tag></tag>
   <elementGuidId>f598d256-4146-453d-98d8-5dd65c5e8021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/ul[2]/div/li[4]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce5c467d-bc53-4940-ab77-f8beb515147c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bottom-menu-item-icon</value>
      <webElementGuid>2ef23c37-2f12-4cbb-846e-bc09dd7bc667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/media/svg/iron-portal/component_analysis.svg</value>
      <webElementGuid>3dd98eba-491b-4528-8764-4c624868cc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/ul[@class=&quot;el-menu el-menu--horizontal ironportal-bottom-menu d-flex align-items-center justify-content-center&quot;]/div[@class=&quot;d-flex&quot;]/li[@class=&quot;el-menu-item bottom-menu-item&quot;]/img[@class=&quot;bottom-menu-item-icon&quot;]</value>
      <webElementGuid>53f19452-1eb9-4508-bf2f-70677240eda2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/ul[2]/div/li[4]/img</value>
      <webElementGuid>25065a21-01de-4838-b2d9-7f0a4b9562d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/img</value>
      <webElementGuid>50b45239-e6b5-45be-852a-a802b605e021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/media/svg/iron-portal/component_analysis.svg']</value>
      <webElementGuid>7754e873-a963-4954-9a3c-0b668df21ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
