<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_COMPONENT LIFE VS OEM_sub-selectable s_ca13ff</name>
   <tag></tag>
   <elementGuidId>726a3adf-8ea5-4714-8754-784288e6d82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.sub-selectable.scatterMarker.setFocusRing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>eb528756-58be-4f94-9bfd-3d74b2a4ffe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-selectable scatterMarker setFocusRing</value>
      <webElementGuid>0b8f2f85-af7b-4ff2-9cc8-8f0f59f146de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sub-selection-object-name</name>
      <type>Main</type>
      <value>markers</value>
      <webElementGuid>57178973-84ee-4353-bcf4-5bb1eb03cd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sub-selection-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a3c728ff-82d1-464f-a4f2-1a03c2063dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 0 0 m -24.15 0 a 24.15 24.15 0 1 0 48.3 0 a 24.15 24.15 0 1 0 -48.3 0</value>
      <webElementGuid>9c7b1ebc-c41d-4317-9435-c70a7879df60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(43.42357020070926,41.65833664181223)</value>
      <webElementGuid>8925de50-ce7c-48ee-9259-31ac2f042cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df3161d6-79f6-4822-bea3-ec0db5eade20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b5aadb0-21c8-45e6-a31e-b998a484b5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fb68eb63-72f7-4af3-8882-6ef44fb05dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c096732b-4945-4a0c-873e-8cdadbc1c258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>380247ec-fc3c-4049-92a8-5febc063c37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pvExplorationHost&quot;)/div[@class=&quot;fillAvailableSpace verticalItemsContainer&quot;]/div[@class=&quot;horizontalItemsContainer&quot;]/exploration[@class=&quot;exploreCanvasToBottom&quot;]/div[@class=&quot;exploration&quot;]/explore-canvas[@class=&quot;explore-canvas-style&quot;]/div[@class=&quot;exploreCanvas themeableElement disableAnimations stylableVisualContainerHeader master-form-factor&quot;]/div[@class=&quot;canvasFlexBox&quot;]/div[@class=&quot;displayAreaContainer newCanvasScrollbar droppableElement ui-droppable&quot;]/div[@class=&quot;displayArea disableAnimations fitToPage&quot;]/div[@class=&quot;visualContainerHost visualContainerOutOfFocus&quot;]/visual-container-repeat[1]/visual-container-group[1]/transform[@class=&quot;isChildSelected selectThrough&quot;]/div[@class=&quot;visualContainerGroup unselectable isChildSelected hideGroupBorder&quot;]/div[@class=&quot;vcGroupBody themableBackgroundColor themableBorderColorSolid&quot;]/visual-container[@class=&quot;visual-container-component&quot;]/transform[@class=&quot;bringToFront&quot;]/div[@class=&quot;visualContainer unselectable readMode hideBorder noVisualTitle visualHeaderAbove droppableElement ui-droppable&quot;]/div[@class=&quot;visualContent&quot;]/div[@class=&quot;vcBody themableBackgroundColor themableBorderColorSolid sub-selectable&quot;]/visual-modern[1]/div[@class=&quot;visual visual-scatterChart customPadding allow-deferred-rendering&quot;]/svg[@class=&quot;cartesianChart&quot;]/svg[@class=&quot;svgScrollable&quot;]/g[@class=&quot;axisGraphicsContext scatterChart playChart&quot;]/g[@class=&quot;mainGraphicsContext&quot;]/svg[@class=&quot;setFocusRing&quot;]/g[@class=&quot;scatterMarkerSeriesGroup&quot;]/path[@class=&quot;sub-selectable scatterMarker setFocusRing&quot;]</value>
      <webElementGuid>179ab081-92fa-460a-a409-7f58a9b065c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BUMA AUSTRALIA - Iron Portal - BUMA Level/iframe</value>
      <webElementGuid>95b60046-909d-4123-a9e8-002d37aa1aa1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
