<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_COMPONENT LIFE VS OEM_sub-selectable s_ca13ff_1</name>
   <tag></tag>
   <elementGuidId>d67c7fac-63e7-4351-aeb8-ba008df1fab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.sub-selectable.scatterMarker.setFocusRing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>720b3c6b-df88-46e4-b1e0-9a5626c60620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-selectable scatterMarker setFocusRing</value>
      <webElementGuid>1aab268e-0223-4988-b484-06e8b0d725ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sub-selection-object-name</name>
      <type>Main</type>
      <value>markers</value>
      <webElementGuid>058b8216-07d2-4bbd-bc55-d207a8bcc9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sub-selection-type</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>987397c3-056e-496b-b20f-c80d71e70f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 0 0 m -24.15 0 a 24.15 24.15 0 1 0 48.3 0 a 24.15 24.15 0 1 0 -48.3 0</value>
      <webElementGuid>a320c440-033f-4f83-9186-974ff6da7dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(43.42357020070926,41.65833664181223)</value>
      <webElementGuid>e808ab1c-9883-4425-bfd7-cd3b94d46760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90e06aa3-6713-4510-9c7c-c054e4d816bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>121b01c8-2ce9-411e-8f09-1f11d4272d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>67870abc-f8f9-4c2b-8d32-0468be5e7892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cec85271-eaa7-4241-9e04-30be0165738a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>44bbe14f-06cb-41ea-adad-ebcaea10d4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pvExplorationHost&quot;)/div[@class=&quot;fillAvailableSpace verticalItemsContainer&quot;]/div[@class=&quot;horizontalItemsContainer&quot;]/exploration[@class=&quot;exploreCanvasToBottom&quot;]/div[@class=&quot;exploration&quot;]/explore-canvas[@class=&quot;explore-canvas-style&quot;]/div[@class=&quot;exploreCanvas themeableElement disableAnimations stylableVisualContainerHeader master-form-factor&quot;]/div[@class=&quot;canvasFlexBox&quot;]/div[@class=&quot;displayAreaContainer newCanvasScrollbar droppableElement ui-droppable&quot;]/div[@class=&quot;displayArea disableAnimations fitToPage&quot;]/div[@class=&quot;visualContainerHost visualContainerOutOfFocus&quot;]/visual-container-repeat[1]/visual-container-group[1]/transform[@class=&quot;isChildSelected selectThrough&quot;]/div[@class=&quot;visualContainerGroup unselectable isChildSelected hideGroupBorder&quot;]/div[@class=&quot;vcGroupBody themableBackgroundColor themableBorderColorSolid&quot;]/visual-container[@class=&quot;visual-container-component&quot;]/transform[@class=&quot;selected bringToFront&quot;]/div[@class=&quot;visualContainer unselectable droppableElement ui-droppable selected swipeable-blocked readMode hideBorder noVisualTitle visualHeaderAbove&quot;]/div[@class=&quot;visualContent&quot;]/div[@class=&quot;vcBody themableBackgroundColor themableBorderColorSolid sub-selectable&quot;]/visual-modern[1]/div[@class=&quot;visual visual-scatterChart customPadding allow-deferred-rendering&quot;]/svg[@class=&quot;cartesianChart&quot;]/svg[@class=&quot;svgScrollable&quot;]/g[@class=&quot;axisGraphicsContext scatterChart playChart&quot;]/g[@class=&quot;mainGraphicsContext&quot;]/svg[@class=&quot;setFocusRing&quot;]/g[@class=&quot;scatterMarkerSeriesGroup&quot;]/path[@class=&quot;sub-selectable scatterMarker setFocusRing&quot;]</value>
      <webElementGuid>9b526ba3-c478-4d51-b830-7a317a92b6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BUMA AUSTRALIA - Iron Portal - BUMA Level/iframe</value>
      <webElementGuid>4f5f87f4-be56-47f5-babf-1944dfe83dbb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
