<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_9999777020</name>
   <tag></tag>
   <elementGuidId>f50bc6ad-3e46-475d-81d3-fa9248e25003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div[2]/div/div/div[3]/table/tbody/tr/td[4]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'cell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57469437-9f2a-4d42-9cae-62c985c986d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>f7196bdd-3d8c-42f5-9ea8-81150a6bf1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9999777020</value>
      <webElementGuid>2946ecd9-9830-41ad-b0b6-9b9e9af1984a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body grid-padding&quot;]/div[@class=&quot;el-table--fit el-table--scrollable-x el-table--enable-row-hover el-table--enable-row-transition el-table&quot;]/div[@class=&quot;el-table__body-wrapper is-scrolling-left&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_1_column_4&quot;]/div[@class=&quot;cell&quot;]</value>
      <webElementGuid>cc2de2f6-e710-4e93-96e1-1348c158ea3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div[2]/div/div/div[3]/table/tbody/tr/td[4]/div</value>
      <webElementGuid>8ffebc42-2933-4e37-89d6-cf9e82bb7d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST0747'])[1]/following::div[2]</value>
      <webElementGuid>31cdb2f2-1dc5-4870-b206-9a97e210ab1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changed by'])[1]/following::div[5]</value>
      <webElementGuid>3663b1f0-4487-4ad6-bdbd-bcfdae5731a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[1]/preceding::div[3]</value>
      <webElementGuid>deb4dfd4-8d18-4e55-80a3-ec16e1cf0608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ben Neill'])[1]/preceding::div[9]</value>
      <webElementGuid>d867b2ed-0302-45ab-b588-c2bd36bc614a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9999777020']/parent::*</value>
      <webElementGuid>865408dc-9110-4606-9832-c0ef7c2bdefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div</value>
      <webElementGuid>6c07301b-c5ee-4f8b-abec-e1f085421b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '9999777020' or . = '9999777020')]</value>
      <webElementGuid>245a4b52-e68b-4922-8950-8b30f4836b26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
