<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter IronPortal</name>
   <tag></tag>
   <elementGuidId>ddee0947-6ec2-482f-91f4-5bc2579303f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div[2]/div[2]/div/div[3]/a/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41494b14-d651-425d-bfd3-5a9118a22e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>1bccb9a9-cb6d-4172-9c08-a7f535bbc4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-go-to-apps btn-label</value>
      <webElementGuid>22d40adf-f75b-4d5c-a409-67a9557b1afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter IronPortal</value>
      <webElementGuid>0e11eb28-9ba1-4380-b913-71b6213b0310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;row gy-5 g-xl-8 m-2 h-250px&quot;]/div[@class=&quot;col-6 col-sm-4 col-md-3 col-lg-20-percent col-xl-2 pe-2 col-xxl-2 ps-0&quot;]/div[@class=&quot;card h-100&quot;]/div[@class=&quot;card-footer&quot;]/a[1]/a[@class=&quot;btn btn-sm btn-go-to-apps btn-label&quot;]</value>
      <webElementGuid>406b6cd4-b645-4464-83b7-34919877c037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div[2]/div[2]/div/div[3]/a/a</value>
      <webElementGuid>c966cc6c-80f1-4d61-af7d-fff0ca0a3f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter IronPortal')]</value>
      <webElementGuid>9e5efd9c-f8fe-4e70-a23f-c650548b7c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Technology Platform that provides critical component condition information.'])[1]/following::a[2]</value>
      <webElementGuid>b7ca7d17-24f7-4935-82b2-7df2affc35bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter IronLake'])[1]/following::a[2]</value>
      <webElementGuid>ce520593-47a2-4bdb-b122-1789cba05c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Technology Platform containing digital maintenance forms.'])[1]/preceding::a[1]</value>
      <webElementGuid>5bf3b338-f10a-4f4a-ba0c-69f97762e43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter IronForms'])[1]/preceding::a[1]</value>
      <webElementGuid>599c9e77-dd88-4f7e-a1d4-1d2b3153cc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter IronPortal']/parent::*</value>
      <webElementGuid>95baeb81-15bc-474a-998d-96b15498e46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[6]</value>
      <webElementGuid>fbab0d07-87d3-4f2c-92f9-3a518b10560a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/a/a</value>
      <webElementGuid>d4145e84-d5fc-48e5-9623-4647418e3980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Enter IronPortal' or . = 'Enter IronPortal')]</value>
      <webElementGuid>c4458414-20bc-4840-a3cf-80693faffc14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
