<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter IronForms</name>
   <tag></tag>
   <elementGuidId>f6e99946-205a-4b12-a908-6e90c2e38930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div[2]/div[3]/div/div[3]/a/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>685feaf2-4c00-4722-9f58-8bcea83a7c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>70b84a54-69b2-4403-ad61-8f39838164a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-go-to-apps btn-label</value>
      <webElementGuid>ec08cd5e-3b51-454e-a1ee-8bfc8f82b916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter IronForms</value>
      <webElementGuid>13fdb4c2-c951-4696-9403-7a8e6bd66657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;row gy-5 g-xl-8 m-2 h-250px&quot;]/div[@class=&quot;col-6 col-sm-4 col-md-3 col-lg-20-percent col-xl-2 pe-2 col-xxl-2 ps-0&quot;]/div[@class=&quot;card h-100&quot;]/div[@class=&quot;card-footer&quot;]/a[1]/a[@class=&quot;btn btn-sm btn-go-to-apps btn-label&quot;]</value>
      <webElementGuid>1f6d321b-856a-4d8a-9e78-81b2b508d993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div[2]/div[3]/div/div[3]/a/a</value>
      <webElementGuid>c0a890d6-88d5-4ebd-94fa-533809a467ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter IronForms')]</value>
      <webElementGuid>fb99baf4-5202-4590-abf2-53ac630ed767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Technology Platform containing digital maintenance forms.'])[1]/following::a[2]</value>
      <webElementGuid>50052bc7-d674-4555-b408-7793752d25c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter IronPortal'])[1]/following::a[2]</value>
      <webElementGuid>53eaae20-dde1-47c6-a90a-e115a12cc096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter IronForms']/parent::*</value>
      <webElementGuid>50b58198-a3b5-40e3-b64d-a2fbad9a2e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[7]</value>
      <webElementGuid>69c3c91e-ed98-40e7-88ee-be02dd3686e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/a/a</value>
      <webElementGuid>8d2e9707-224b-4540-b44e-776358ecd44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Enter IronForms' or . = 'Enter IronForms')]</value>
      <webElementGuid>5eb6bfea-8728-4928-ab41-dccf545f1aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
