<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Online_ring d-flex justify-content-center</name>
   <tag></tag>
   <elementGuidId>afbc1337-3242-46fd-85a2-0aaaaa45c6c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ring.d-flex.justify-content-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slot-container']/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31df81db-9131-4c05-a45a-383e62ad4021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ring d-flex justify-content-center</value>
      <webElementGuid>dda6e3af-72a8-40f6-8a89-dab47f3a97f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot-container&quot;)/div[@class=&quot;d-flex flex-column justify-content-center align-items-end camera-container&quot;]/div[@class=&quot;w-9 py-3 d-flex flex-column justify-content-center align-items-center bg-dark&quot;]/div[@class=&quot;photo-button mb-2&quot;]/div[@class=&quot;ring d-flex justify-content-center&quot;]</value>
      <webElementGuid>d6062b59-d8b8-4b7e-ae69-f10a53e5d5c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot-container']/div/div/div/div[2]</value>
      <webElementGuid>2483cae6-9e28-4a29-9b09-7f69e5468c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::div[13]</value>
      <webElementGuid>6eec48c9-acea-4b7e-a6a7-35685d1469f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ben Neill'])[1]/preceding::div[16]</value>
      <webElementGuid>855bed76-fe03-442f-9466-17e29d280f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>54ca5e39-9d69-48a9-ad95-4ac406dfcafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
