<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DT0053 - CAT 777D - 1000 Hour Service - _d87edd</name>
   <tag></tag>
   <elementGuidId>0fc503aa-d373-49b8-804a-04f4976058c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[3]/div[2]/div/div[2]/div/div/div[2]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f5fc1fe6-62cd-40ec-87bb-33eff3d2e40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>82e73cc6-1756-4810-94ab-1d1f661d7815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DT0053 - CAT 777D - 1000 Hour Service - 9931052302</value>
      <webElementGuid>e976d5ed-1211-4c24-8a22-c6595610033f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container h-100 p-0&quot;]/div[@class=&quot;row mx-0&quot;]/div[3]/div[@class=&quot;el-overlay&quot;]/div[@class=&quot;el-dialog el-dialog--center&quot;]/div[@class=&quot;el-dialog__body&quot;]/div[@class=&quot;row select-search&quot;]/div[@class=&quot;input-group col-md-4&quot;]/div[@class=&quot;option-wrapper m-0&quot;]/ul[@class=&quot;text-left&quot;]/li[@class=&quot;option&quot;]</value>
      <webElementGuid>02fbc441-0cef-4d18-9c93-4d42a129fae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div[2]/div/div[2]/div/div/div[2]/ul/li</value>
      <webElementGuid>2e852910-d025-4261-af43-fda79719cbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding Services'])[1]/following::li[1]</value>
      <webElementGuid>3a865482-4614-4adb-a269-d88ac07872f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commence Digital Service'])[1]/following::li[1]</value>
      <webElementGuid>efa439b4-2d4a-4dc4-8593-bba42f02025b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commence Digital Component Intervention'])[1]/preceding::li[1]</value>
      <webElementGuid>68b247b0-01f8-40d4-a009-7ffb312c5d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DT0053 - CAT 777D - 1000 Hour Service - 9931052302']/parent::*</value>
      <webElementGuid>018ed5e7-5392-4ffa-abde-1883094ed99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>c63ccf2f-8d4a-4d72-9c52-375b5f9c0c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'DT0053 - CAT 777D - 1000 Hour Service - 9931052302' or . = 'DT0053 - CAT 777D - 1000 Hour Service - 9931052302')]</value>
      <webElementGuid>ebed2501-4ec8-4475-a59a-679d0b2a24a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
