<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tom Woodward</name>
   <tag></tag>
   <elementGuidId>93aade44-58a3-4ca8-b02b-8f053255b84c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-collapse-content-9038']/div/div/div/div/div/div/div[2]/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f6dd067a-f41a-4a0f-8d8e-22aa4a2a2fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b76c4ba3-7a52-43b2-bcf9-1dab0eb0859f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tom Woodward</value>
      <webElementGuid>cc247d82-e0c7-412e-a090-8b5cb6c92ed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-9038']/div/div/div/div/div/div/div[2]/ul/li[2]</value>
      <webElementGuid>dc0d62c3-83ee-4cdd-8ce1-784be4c91233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jamie Brady'])[1]/following::li[1]</value>
      <webElementGuid>8cfbeb46-7cf2-4a57-857f-fba1a52ed608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labour Personnel Name'])[1]/following::li[2]</value>
      <webElementGuid>8c9d5668-12e2-45d2-bc8e-4467eb98adf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actual Service Start (each labour personnel)'])[1]/preceding::li[1]</value>
      <webElementGuid>fba15782-27c1-4737-b1d2-64632b460fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift'])[1]/preceding::li[1]</value>
      <webElementGuid>400a51cf-45ad-455d-96e7-285cac9273de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tom Woodward']/parent::*</value>
      <webElementGuid>cb6252e1-bfc9-4fe7-9c3a-68bfabf45fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>0812e898-8fa4-45aa-8b77-34d6b3ba23b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Tom Woodward' or . = 'Tom Woodward')]</value>
      <webElementGuid>3eae012b-0098-487a-95f6-2b1547e03faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-4755']/div/div/div/div/div/div/div[2]/ul/li[2]</value>
      <webElementGuid>6fc14d12-fabf-4598-a1aa-20dda4a99df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-3766']/div/div/div/div/div/div/div[2]/ul/li</value>
      <webElementGuid>ec733946-5883-4015-b319-5f2154270ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labour Personnel Name'])[1]/following::li[1]</value>
      <webElementGuid>8444d823-a064-43c3-8314-fb7296710478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Labour Personnel'])[1]/following::li[1]</value>
      <webElementGuid>81243b94-9927-4331-ba52-a1763e77e339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>705650e4-c8fe-476e-988f-f55808c167a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
