<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service Size_el-input__inner</name>
   <tag></tag>
   <elementGuidId>7404ffb1-1fd4-441b-ab15-dbf92f1aa172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.el-input.el-input--suffix.is-focus > input.el-input__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ca663a4-f308-48b6-859c-6a5e8c147c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>c10bdf19-93f7-41e4-b5c9-d24b07171c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1302b607-01d9-4fe3-be56-61cc7de1f5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ec4e3cf7-108b-4ca6-a059-01244607693e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Service Size</value>
      <webElementGuid>22dfe78b-7668-41ba-ab34-858e63306584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_filter_form&quot;)/div[@class=&quot;col-md-6 fv-row fv-plugins-icon-container&quot;]/div[@class=&quot;fv-row&quot;]/div[@class=&quot;el-form-item col&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-select w-100&quot;]/div[@class=&quot;select-trigger&quot;]/div[@class=&quot;el-input el-input--suffix is-focus&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>72b4db33-278e-4322-9650-c6276544a4f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>9e52199d-5a46-41a0-bb68-f9a2481140d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_filter_form']/div[4]/div/div/div/div/div/div/input</value>
      <webElementGuid>6201f674-bf98-4b3e-86b3-91fda1525010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/input</value>
      <webElementGuid>623941a0-9cda-4c11-bacc-da903f7efbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Add Service Size']</value>
      <webElementGuid>381534b8-161e-4244-918e-988d45adc7e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
