<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Planned Service Date_dateService</name>
   <tag></tag>
   <elementGuidId>b5573822-fd3f-406e-8ae1-3816f2fb24ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dateService']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dateService&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>727a6e98-ac48-45d8-8a6b-80d97fb64e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>14a30009-758c-4dd3-a103-ca827215244d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dateService</value>
      <webElementGuid>822d3f73-1f0e-4de8-95d1-6f3bed5397c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-popper-7061</value>
      <webElementGuid>9ae7f94d-89a3-4ef0-a5dc-698880decae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad80edca-1f90-4d04-b7d7-6db33a6318f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6aa52df2-245e-4808-85b2-a49477369666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Planned Service Date</value>
      <webElementGuid>57f6b916-d1db-495a-bb4c-51dacaa8e703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_filter_form&quot;)/div[@class=&quot;col-md-6 fv-row fv-plugins-icon-container&quot;]/div[@class=&quot;fv-row&quot;]/div[@class=&quot;el-form-item&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-input el-input--prefix el-input--suffix el-date-editor el-date-editor--date w-100&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>b1358161-4827-4d92-99aa-56291bed4049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dateService']</value>
      <webElementGuid>3602ada0-05c7-4d53-a97f-3162f9702c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_filter_form']/div[5]/div/div/div/div/input</value>
      <webElementGuid>960fc260-b6af-4d02-bb99-9d15ec637cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>23c2658d-5fbd-42b5-86a3-f7c8ed04cbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dateService' and @type = 'text' and @placeholder = 'Add Planned Service Date']</value>
      <webElementGuid>7527ad49-0ba5-4a5c-aada-e1c8bc45daeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
